"""Sync models with database

Revision ID: 77eed2a2efc4
Revises: bc3172c02bfa
Create Date: 2026-07-15 10:40:18.236093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '77eed2a2efc4'
down_revision: Union[str, None] = 'bc3172c02bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('bill_number', table_name='bills')
    op.drop_index('idx_bills_bill_number', table_name='bills')
    op.drop_index('idx_bills_client_id', table_name='bills')
    op.drop_index('idx_bills_user_id', table_name='bills')
    op.drop_table('bills')
    op.drop_index('idx_ca_masters_user_id', table_name='ca_masters')
    op.drop_index('user_id', table_name='ca_masters')
    op.drop_table('ca_masters')
    op.drop_index('idx_documents_client_id', table_name='documents')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_bill_items_bill_id', table_name='bill_items')
    op.drop_table('bill_items')
    op.drop_index('idx_client_fee_matches_applied', table_name='client_fee_matches')
    op.drop_index('idx_client_fee_matches_client_id', table_name='client_fee_matches')
    op.drop_table('client_fee_matches')
    op.drop_index('idx_notifications_is_read', table_name='notifications')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_published_fee_pamplate_id', table_name='published_fee_pamplate')
    op.drop_table('published_fee_pamplate')
    op.drop_index('idx_fee_categories_code', table_name='fee_categories')
    op.drop_index('idx_fee_categories_user_id', table_name='fee_categories')
    op.drop_table('fee_categories')
    op.drop_index('idx_published_fee_pamphlet_client_id', table_name='published_fee_pamphlet')
    op.drop_index('idx_published_fee_pamphlet_user_id', table_name='published_fee_pamphlet')
    op.drop_table('published_fee_pamphlet')
    op.alter_column('client_masters', 'client_type',
               existing_type=mysql.ENUM('INDIVIDUAL', 'BUSINESS', 'HUF', 'PARTNERSHIP', 'COMPANY', 'LLP'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('client_masters', 'status',
               existing_type=mysql.ENUM('ACTIVE', 'INACTIVE', 'PENDING', 'SUSPENDED'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('client_masters', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=True)
    op.alter_column('client_masters', 'total_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('client_masters', 'paid_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('client_masters', 'pending_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('client_masters', 'fee_status',
               existing_type=mysql.ENUM('PENDING', 'PARTIAL', 'PAID', 'OVERDUE'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('client_masters', 'fee_confirmed',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=True)
    op.alter_column('client_masters', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('client_masters', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               nullable=True)
    op.drop_index('idx_client_masters_ca_user_id', table_name='client_masters')
    op.drop_index('idx_client_masters_user_id', table_name='client_masters')
    op.alter_column('data', 'uploaded_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('data', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('fy_master', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=True)
    op.alter_column('fy_master', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('fy_master', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               nullable=True)
    op.drop_index('idx_fy_master_year', table_name='fy_master')
    op.drop_index('year', table_name='fy_master')
    op.create_index(op.f('ix_fy_master_id'), 'fy_master', ['id'], unique=False)
    op.create_index(op.f('ix_fy_master_year'), 'fy_master', ['year'], unique=True)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('SUPER_ADMIN', 'CA', 'STAFF', 'CLIENT'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_super_admin',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               nullable=True)
    op.drop_index('email', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('username', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('username', 'users', ['username'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('email', 'users', ['email'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'),
               type_=mysql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('current_timestamp()'),
               type_=mysql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('users', 'is_super_admin',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('SUPER_ADMIN', 'CA', 'STAFF', 'CLIENT'),
               server_default=sa.text("'CA'"),
               existing_nullable=False)
    op.drop_index(op.f('ix_fy_master_year'), table_name='fy_master')
    op.drop_index(op.f('ix_fy_master_id'), table_name='fy_master')
    op.create_index('year', 'fy_master', ['year'], unique=False)
    op.create_index('idx_fy_master_year', 'fy_master', ['year'], unique=False)
    op.alter_column('fy_master', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'),
               type_=mysql.TIMESTAMP(),
               nullable=False)
    op.alter_column('fy_master', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('current_timestamp()'),
               type_=mysql.TIMESTAMP(),
               nullable=False)
    op.alter_column('fy_master', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('data', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('data', 'uploaded_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.create_index('idx_client_masters_user_id', 'client_masters', ['user_id'], unique=False)
    op.create_index('idx_client_masters_ca_user_id', 'client_masters', ['ca_user_id'], unique=False)
    op.alter_column('client_masters', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'),
               type_=mysql.TIMESTAMP(),
               nullable=False)
    op.alter_column('client_masters', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('current_timestamp()'),
               type_=mysql.TIMESTAMP(),
               nullable=False)
    op.alter_column('client_masters', 'fee_confirmed',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('client_masters', 'fee_status',
               existing_type=mysql.ENUM('PENDING', 'PARTIAL', 'PAID', 'OVERDUE'),
               server_default=sa.text("'PENDING'"),
               existing_nullable=True)
    op.alter_column('client_masters', 'pending_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=True)
    op.alter_column('client_masters', 'paid_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=True)
    op.alter_column('client_masters', 'total_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=True)
    op.alter_column('client_masters', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('client_masters', 'status',
               existing_type=mysql.ENUM('ACTIVE', 'INACTIVE', 'PENDING', 'SUSPENDED'),
               server_default=sa.text("'PENDING'"),
               existing_nullable=True)
    op.alter_column('client_masters', 'client_type',
               existing_type=mysql.ENUM('INDIVIDUAL', 'BUSINESS', 'HUF', 'PARTNERSHIP', 'COMPANY', 'LLP'),
               server_default=sa.text("'INDIVIDUAL'"),
               existing_nullable=True)
    op.create_table('published_fee_pamphlet',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fee_data', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False),
    sa.Column('total_fee', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('total_gst', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('grand_total', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('is_viewed', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('viewed_at', mysql.DATETIME(), nullable=True),
    sa.Column('accepted_at', mysql.DATETIME(), nullable=True),
    sa.Column('rejected_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_masters.id'], name='published_fee_pamphlet_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='published_fee_pamphlet_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_published_fee_pamphlet_user_id', 'published_fee_pamphlet', ['user_id'], unique=False)
    op.create_index('idx_published_fee_pamphlet_client_id', 'published_fee_pamphlet', ['client_id'], unique=False)
    op.create_table('fee_categories',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('base_fee', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('gst_rate', mysql.DECIMAL(precision=5, scale=2), server_default=sa.text('18.00'), nullable=True),
    sa.Column('keywords', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('fee_type', mysql.VARCHAR(length=50), server_default=sa.text("'basic'"), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('is_system_default', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_published', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('published_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fee_categories_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_fee_categories_user_id', 'fee_categories', ['user_id'], unique=False)
    op.create_index('idx_fee_categories_code', 'fee_categories', ['code'], unique=False)
    op.create_table('published_fee_pamplate',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fee_data', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False),
    sa.Column('total_fee', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_gst', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('grand_total', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_viewed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('viewed_at', mysql.DATETIME(), nullable=True),
    sa.Column('accepted_at', mysql.DATETIME(), nullable=True),
    sa.Column('rejected_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_masters.id'], name='published_fee_pamplate_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='published_fee_pamplate_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_published_fee_pamplate_id', 'published_fee_pamplate', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('message', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('data', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_table('client_fee_matches',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fee_category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('document_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fee_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('gst_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('matched_keywords', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('match_confidence', mysql.DECIMAL(precision=5, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('is_auto_matched', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('is_applied', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_masters.id'], name='client_fee_matches_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='client_fee_matches_ibfk_3', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fee_category_id'], ['fee_categories.id'], name='client_fee_matches_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_client_fee_matches_client_id', 'client_fee_matches', ['client_id'], unique=False)
    op.create_index('idx_client_fee_matches_applied', 'client_fee_matches', ['is_applied'], unique=False)
    op.create_table('bill_items',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('bill_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fee_category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('document_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('gst_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name='bill_items_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='bill_items_ibfk_3', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fee_category_id'], ['fee_categories.id'], name='bill_items_ibfk_2', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_bill_items_bill_id', 'bill_items', ['bill_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fy_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('document_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('file_title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('file_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('file_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.ENUM('PENDING_UPLOAD', 'UPLOADED', 'APPROVED', 'REJECTED', 'RE_UPLOAD_REQUIRED'), server_default=sa.text("'PENDING_UPLOAD'"), nullable=True),
    sa.Column('gdrive_file_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('gdrive_web_link', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('local_path', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.Column('uploaded_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.Column('uploaded_by', mysql.VARCHAR(length=50), server_default=sa.text("'client'"), nullable=True),
    sa.Column('fee_confirmed', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('fee_confirmed_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_masters.id'], name='documents_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fy_id'], ['fy_master.id'], name='documents_ibfk_3', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='documents_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_index('idx_documents_client_id', 'documents', ['client_id'], unique=False)
    op.create_table('ca_masters',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('firm_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('firm_address', mysql.TEXT(), nullable=True),
    sa.Column('gst_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('pan_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('specialization', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('experience', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('registration_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ca_masters_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'ca_masters', ['user_id'], unique=False)
    op.create_index('idx_ca_masters_user_id', 'ca_masters', ['user_id'], unique=False)
    op.create_table('bills',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('bill_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status', mysql.ENUM('DRAFT', 'PENDING', 'ACCEPTED', 'REJECTED', 'PAID', 'CANCELLED'), server_default=sa.text("'PENDING'"), nullable=True),
    sa.Column('total_amount', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('gst_amount', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('grand_total', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('accepted_at', mysql.DATETIME(), nullable=True),
    sa.Column('rejected_at', mysql.DATETIME(), nullable=True),
    sa.Column('paid_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_masters.id'], name='bills_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='bills_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_bills_user_id', 'bills', ['user_id'], unique=False)
    op.create_index('idx_bills_client_id', 'bills', ['client_id'], unique=False)
    op.create_index('idx_bills_bill_number', 'bills', ['bill_number'], unique=False)
    op.create_index('bill_number', 'bills', ['bill_number'], unique=False)
    # ### end Alembic commands ###
